### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by majuss** [KfirShainholtz/grafana-http-client#1]
Could you please briefly describe how to use your library, in a minimal example?
Thanks a lot!

**Comment by KfirShainholtz** [comment]
Hey, sorry for not answering,
Unfortunately I had to move to a minimal Java implementation of this package, even though it's fully working (when using Grafana v5.2.3). 

I'm adding a quick readme for setup & usage of the library. feel free to add any beneficial code, or let me know if you want something
