### ISSUE TITLE
Log events to graphana

### ISSUE THREAD

**Issue by ScriptedAlchemy** [KfirShainholtz/grafana-http-client#2]
Is it possible to use this tool to post events to Grafana? I’m looking for a way to log frontend events to graphana dashboards for runtime analysts. Any ideas how to do this. The idea bing to measure timetime from request to response app the way to the browser. Universal metrics grabbing. Was looking to do it with just normal HTTP posts to a node endpoint or something.  But struggling to find solutions

**Comment by KfirShainholtz** [comment]
Are you trying to measure Grafana timing?
If you're trying to use a universal metrics (for your actual data, like measuring timing between client and an RDS server), I think that this shouldn't be your go-to client to use;

This package is simplifying Grafana public API usage, I think you're describing something closer to an elasticsearch datasource that'll hold your data (are the events numeric?) or Zipkin (https://zipkin.io/)?
